[package]
name = "remote_execute_macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.86"
quote = "1.0.36"
serde = "1.0.205"
serde_closure = "0.3.3"
syn = "2.0.72"
tokio = "1.39.2"
tonic = "0.12.1"

