[package]
name = "basemodules"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.76"
serde = "1.0.205"
async-trait = "0.1.81"
serde_json = "1.0.122"
tonic = "0.12.1"
tonic-build = "0.9"
rayon = "1.10.0"
futures = "0.3.30"
